import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins=Poppins({
  variable: "--font-poppins",
  weight: '300',
  style: 'normal',
})

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({children}:Readonly<{children:React.ReactNode}>) {

  
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <div className="w-full relative flex items-center justify-center">
           <Navbar/>
           </div>
        {children}
      </body>
    </html>
  );
}
